from typing import TypedDict, List

from models.profile_schema import Profile
from models.matched_job_schema import MatchedJob


class CareerState(TypedDict):
    """
    Shared state used by all LangGraph agents.
    """

    # Extracted resume text
    resume_text: str

    # Structured candidate profile
    profile: Profile | None

    # Search query generated by Search Agent
    search_query: str

    # Tavily search results
    jobs: List[dict]

    # Top 3 matched jobs
    matched_jobs: List[MatchedJob]

    # Generated cover letter
    cover_letter: str